name: 'My Local Action'
description: 'Custom steps to perform from a local action in the same repo as the workflow'
inputs:
  git-tag-release:
    description: 'The git tag that was assigned to the release'
    required: true
outputs:
  output-folder:
    description: 'Folder in which result files will be put'
    value: ${{ steps.copy-files-in-output.outputs.output-folder }}
runs:
  using: 'composite'
  steps:
    - name: Print the path
      run: pwd
      shell: bash

    - name: List the current folder
      run: ls -l .
      shell: bash

    - name: Show current branch
      run: git rev-parse --short HEAD
      shell: bash

    - name: Copy file into output folder
      id: copy-files-in-output
      run: |
        echo "Copying a file into the output folder"
        cd ..
        mkdir output-folder
        cd output-folder
        OUTPUT_FOLDER=$(pwd)
        cp $GITHUB_ACTION_PATH/dummy1.txt $OUTPUT_FOLDER/dumm1.txt
        echo "output-folder=${OUTPUT_FOLDER}" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
        GIT_TAG_RELEASE: ${{ inputs.git-tag-release }}

