name: 'My Local Action'
description: 'Custom steps to perform from a local action in the same repo as the workflow'
inputs:
  git-tag-release:
    description: 'The git tag that was assigned to the release'
    required: true
outputs:
  output-folder:
    description: 'Folder in which result files will be put'
    value: ${{ steps.copy-files-in-output.outputs.output-folder }}
runs:
  using: 'composite'
  steps:
    - name: Print the path
      run: pwd
      shell: bash

    - name: List the current folder
      run: ls -l .
      shell: bash

    - name: Show current branch
      run: git rev-parse --short HEAD
      shell: bash

    - name: Copy file into output folder
      id: copy-files-in-output
      run: |
        echo "Copying a file into the output folder"
        mkdir -p ../output-folder && cp dummy1.txt ../output-folder/dummy1.txt
        cd ../output-folder
        OUTPUT_FOLDER=$(pwd)
        echo "output-folder=${OUTPUT_FOLDER}" >> $GITHUB_OUTPUT
      shell: bash

    - name: Grab input and check working path
      run: |
        pwd
        echo "The published tag release is $GIT_TAG_RELEASE"
      shell: bash  
      env:
        GIT_TAG_RELEASE: ${{ inputs.git-tag-release }}

