on:
  release:
    types: [created]

jobs:
  hello_world_job_linux:
    runs-on: ubuntu-latest
    name: A job to say hello in Linux
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: visomar/hello-world-composite-action@v1.2
        with:
          who-to-greet: 'Vicente'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}

  hello_world_job_windows:
    runs-on: windows-latest
    name: A job to say hello in Windows
    steps:
      - uses: actions/checkout@v4
      - id: foo
        uses: visomar/hello-world-composite-action@v1.2
        with:
          who-to-greet: 'Vicente'
      - run: echo random-number "$RANDOM_NUMBER"
        shell: bash
        env:
          RANDOM_NUMBER: ${{ steps.foo.outputs.random-number }}

  my_custom_local_action_used:
    runs-on: ubuntu-latest
    name: A job to test local action
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      - name: Load some configuration from YAML
        uses: doughepi/yaml-env-action
        with:
          files: ./.github/config.yml # Pass a space-separated list of configuration files. Rightmost files take precedence.
      - name: Test of config variables:
        run: |
          echo "Simple key: ${{ env.YEPE }}"
          echo "Nested key: ${{ env.MY_VALUE }}"
          echo "Camel case key: ${{ env.FIRST_KEY }}"
          echo "Kebab case key: ${{ env.SECOND_KEY }}"
          echo "Snake case key: ${{ env.THIRD_KEY }}"
        shell: bash
      - name: Run steps in local action
        uses: ./my-local-action
        with:
          git-tag-release: ${{ github.event.release.tag_name }}

